#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-datanucleus-core
Version  : 3.2.10
Release  : 1
URL      : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10-sources.jar
Source0  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10-sources.jar
Source1  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.jar
Source2  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-datanucleus-core-data = %{version}-%{release}

%description
Core
====
This project is the prerequisite of any application using DataNucleus.
Other DataNucleus projects depend on this project.

%package data
Summary: data components for the mvn-datanucleus-core package.
Group: Data

%description data
data components for the mvn-datanucleus-core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10-sources.jar
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.jar
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.pom
